### ISSUE TITLE
Text BASIC files will not show up

### ISSUE THREAD

**Issue by leventp** [paulscottrobson/neo6502-firmware#46]
The text BASIC files with .bsc  extension will load but LIST shows nothing. I extracted sample files in the Windows environment. Not sure extra CR is the problem here. Note that the USB stick I am using is formatted with FAT32.

**Comment by paulscottrobson** [comment]
My bad. You can't load text basic files in at present, only the BAS files which are tokenised. 

If you want to use text files you can see an example in the file crossdev.zip for the emulator which converts it with a Python script.  

It is possible to 'squirt' these down the serial line now, though this is partly dependent on the other bug which appears to be caused by Serial.
