### ISSUE TITLE
Implement insertion and deletion

### ISSUE THREAD

**Issue by leventp** [paulscottrobson/neo6502-firmware#55]
The  following Control Codes (described in the api document) are not working for me (in edit mode):

CTRL+E  : No insert effect
CTRL+G : No effect 
CTRL+F : Page down? Not sure what this does
CTRL+X : Draws a pipe char as cursor first time then no effect
CTRL+Z : No effect
CTRL+[ : prints "{"

**Comment by paulscottrobson** [comment]
It's a documentation issue.  Console codes have two functions ; they are keyboard maps - so INSERT should generate the Ctrl+E code, and they are console out functions. 

Insert needs implementing. At present you can't insert a character in a line when editing on the screen and this is an issue. Removing matters much less because spaces are removed from the tokenised code anyway. 

Hence the change of the title.

**Comment by leventp** [comment]
Note that Backspace is not working either. Only blanking out the character next to the left of the cursor. Making editing lines of BASIC  a bit difficult.

**Comment by paulscottrobson** [comment]
Same issue. Apart from strings doesn’t matter because spaces aren’t stored anywaySent from my iPhoneOn 2 Feb 2024, at 23:05, leventp ***@***.***> wrote:﻿
Note that Backspace is not working either. Only blanking out the character next to the left of the cursor. Making editing lines of BASIC  a bit difficult.

**Comment by paulscottrobson** [comment]
Insert and Delete and Backspace now work.
